name: derde_divisie
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  logging: ^1.2.0
  http: ^1.2.2
  share_plus: ^10.1.4
  video_player: ^2.10.1

  # Announcements
  firebase_remote_config: any
  shared_preferences: any

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  cloud_functions: ^6.0.0

  # Afbeeldingen & Uploads
  image_picker: ^1.1.2
  file_picker: ^10.2.0

  # Websupport voor image_picker
  universal_html: ^2.2.2

  # Extra
  uuid: ^4.0.0
  web: ^1.1.1
  url_launcher: ^6.3.0
  firebase_analytics: ^12.4.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/default_avatar.webp
    - assets/logo_dd.png
    - assets/logo_derdediv.png
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_dd.png"

flutter_native_splash:
  color: "#050807"
  image: assets/logo_derdediv.png
  android: true
  ios: true
  web: true
  branding_mode: bottom
