// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvxFqRSQI7JtaJcKUj4ELPiCmPfrdtHlA',
    appId: '1:183305663290:web:686546c7cf3419389c5603',
    messagingSenderId: '183305663290',
    projectId: 'derde-divisie-app',
    authDomain: 'derde-divisie-app.firebaseapp.com',
    storageBucket: 'derde-divisie-app.appspot.com',
    measurementId: 'G-QGCHNXV76M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGGqcvU1IQc_BRIIgf9fJZAvn2DHNvVkU',
    appId: '1:183305663290:android:1dc837d62a546f519c5603',
    messagingSenderId: '183305663290',
    projectId: 'derde-divisie-app',
    storageBucket: 'derde-divisie-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxiHMA5BaLnJIJ_iYcYhiPcfokWHrgSJE',
    appId: '1:183305663290:ios:a3fe7fce5fcf5afa9c5603',
    messagingSenderId: '183305663290',
    projectId: 'derde-divisie-app',
    storageBucket: 'derde-divisie-app.appspot.com',
    iosBundleId: 'com.example.derdeDivisie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxiHMA5BaLnJIJ_iYcYhiPcfokWHrgSJE',
    appId: '1:183305663290:ios:a3fe7fce5fcf5afa9c5603',
    messagingSenderId: '183305663290',
    projectId: 'derde-divisie-app',
    storageBucket: 'derde-divisie-app.appspot.com',
    iosBundleId: 'com.example.derdeDivisie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvxFqRSQI7JtaJcKUj4ELPiCmPfrdtHlA',
    appId: '1:183305663290:web:fb0f9d29956bf5539c5603',
    messagingSenderId: '183305663290',
    projectId: 'derde-divisie-app',
    authDomain: 'derde-divisie-app.firebaseapp.com',
    storageBucket: 'derde-divisie-app.appspot.com',
    measurementId: 'G-X9ESYBLF1M',
  );
}
