const fs=require('fs');const edit=(p,f)=>fs.writeFileSync(p,f(fs.readFileSync(p,'utf8')));
edit('functions/src/result-domain.ts',s=>s.replace('h: r[0], a: r[1], round};','h: r[0], a: r[1], round, day: deadline(m) ?? 0};').replace('played: 0, wins: 0, draws: 0, losses: 0, goalsFor: 0, goalsAgainst: 0, points: 0,','played: 0, wins: 0, draws: 0, losses: 0, goalsFor: 0, goalsAgainst: 0, points: 0, form: [],').replace('for (const c of Object.values(contributions) as Data[]) {','for (const c of (Object.values(contributions) as Data[]).filter(Boolean).sort((a,b)=>(b.day ?? b.round)-(a.day ?? a.round))) {').replace('row.played++; row.goalsFor += gf; row.goalsAgainst += ga;','row.played++; row.goalsFor += gf; row.goalsAgainst += ga;\n      if(row.form.length<5)row.form.push(gf>ga?"W":gf===ga?"G":"V");'));
edit('lib/features/derde_divisie/stand_derde_divisie_screen.dart',s=>{
 s=s.replace('return SeasonPaths.currentSeasonStandings.snapshots();',"return SeasonPaths.currentSeasonStandings.where('division', isEqualTo: _divisieCode(divisie)).snapshots();");
 s=s.replace(/  Future<Map<String, List<String>>> _vormMapFuture\(\) async \{[\s\S]*?\r?\n  \}\r?\n\r?\n/, '');
 s=s.replace('entries.sort((a, b) {\r\n      int c;','entries.sort((a, b) {\r\n      if (a.positie > 0 && b.positie > 0) return a.positie.compareTo(b.positie);\r\n      int c;').replace('entries.sort((a, b) {\n      int c;','entries.sort((a, b) {\n      if (a.positie > 0 && b.positie > 0) return a.positie.compareTo(b.positie);\n      int c;');
 s=s.replace(/          return FutureBuilder<DivisionData\?>\([\s\S]*?\r?\n          \);\r?\n        \},/,`          if(standSnap.hasError) { return const Center(child: Text('Stand kon niet worden geladen.')); }
          final entries=seasonEntries.isNotEmpty ? seasonEntries : SeasonConfig.teamsForDivision(_divisieCode(divisie)).map((team)=>StandEntry.fromName(team.name)).toList();
          return _buildTable(context: context, entries: entries, vormMap: {for(final entry in entries) entry.code: ((entry.data['form'] as List?) ?? []).map((v)=>v.toString()).toList()});
        },`);
 return s;
});
// Restore explicit, confirmed reset functions with server-owned derived values.
edit('lib/features/moderator/moderator_tools_screen.dart',s=>s.replace("import 'package:flutter/material.dart';","import 'package:flutter/material.dart';\nimport 'package:derde_divisie/features/moderator/reset_eindstand_punten.dart';").replace("label: 'Verwerking opnieuw aanvragen (A & B)'","label: 'Reset eindstandpunten (A & B)'").replace("label: 'Alle wedstrijden opnieuw verwerken'","label: 'VOLLEDIGE RESET (actief seizoen)'").replace('Deze actie vraagt de server alle actuele wedstrijden opnieuw te controleren en verwerken. Brongegevens blijven behouden.','Deze actie verwijdert alle actuele uitslagen en eindstandbonussen. De server draait bijbehorende wedstrijdpunten terug. Voorspellingen blijven behouden.').replace('Deze actie vraagt de server alle actuele wedstrijden opnieuw te controleren en verwerken.','Deze actie draait de eindstandbonussen van het actieve seizoen terug. Wedstrijdpunten blijven behouden.').replace('action: tools.hardeResetEnHerberekenAlles,','action: resetEindstandPuntenBeide,').replace("errorPrefix: 'Fout bij volledige reset'","errorPrefix: 'Fout bij volledige reset'").replace(/action: resetEindstandPuntenBeide,([\s\S]*?)errorPrefix: 'Fout bij volledige reset'/,'action: volledigeResetAllesNaarNul,$1errorPrefix: \'Fout bij volledige reset\'').replace("title: 'Volledige reset uitvoeren?'","title: 'Actuele uitslagen verwijderen?'").replace("confirmText: 'Opnieuw verwerken'","confirmText: 'Resetten'"));
