const fs=require('fs');const edit=(p,f)=>fs.writeFileSync(p,f(fs.readFileSync(p,'utf8')));
for(const p of ['tools/audit_result_processing.cjs','tools/benchmark_result_processing.cjs'])edit(p,s=>`const adminRequire=require('node:module').createRequire(require('node:path').resolve(__dirname,'../functions/package.json'));\n`+s.replace(/require\('\.\.\/functions\/node_modules\/(firebase-admin\/[^']+)'\)/g,"adminRequire('$1')"));
edit('test/features/moderator_dashboard_access_test.dart',s=>s.replace("expect(find.text('CSV-exports'), findsNothing);","expect(find.text('CSV-exports'), findsNothing);\n    completer.complete(false);\n    await tester.pumpAndSettle();"));
edit('test/features/eindstand_points_structure_test.dart',s=>s.replace("expect(source, contains('SeasonPaths.currentSeasonMatches'));","expect(source, contains(\"httpsCallable('processFinalStandings')\"));\n    final server = File('functions/src/final-points.ts').readAsStringSync();\n    expect(server, contains('seasons/\${ACTIVE_SEASON}/matches'));\n    expect(server, contains('runTransaction'));").replace("expect(source, contains(\"'punten_A' : 'punten_B'\"));","expect(server, contains('punten_A'));\n    expect(server, contains('punten_B'));").replace("expect(source, contains(\"{'totalen': hoogste}\"));","expect(server, contains('Math.max(a, b)'));"));
// Active poule sources use the same matches as result processing.
for(const p of ['lib/features/poules/poule_voorspellingen_screen.dart','lib/features/poules/wedstrijden_poule_dda_screen.dart','lib/features/poules/wedstrijden_poule_ddb_screen.dart','lib/features/poules/voorspel_competitie_poule_screen.dart'])edit(p,s=>{
 if(!s.includes("import 'package:derde_divisie/data/firestore/season_paths.dart';"))s="import 'package:derde_divisie/data/firestore/season_paths.dart';\n"+s;
 s=s.replace(/FirebaseFirestore.instance\s*\.collection\('matches'\)/g,'SeasonPaths.currentSeasonMatches');
 if(p.includes('wedstrijden_poule'))s=s.replace(".where('competitie', isEqualTo: _fsCompetitie)",".where('division', isEqualTo: '"+(p.includes('_dda_')?'A':'B')+"')").replace(".where('speelronde', isEqualTo: speelronde)",".where('round', isEqualTo: speelronde)").replace("data['datum'] ?? data['timestamp']","data['scheduledAt'] ?? data['date'] ?? data['datum'] ?? data['timestamp']").replace("data['uitslagThuis'];","data['homeScore'] ?? data['uitslagThuis'];").replace("data['uitslagUit'];","data['awayScore'] ?? data['uitslagUit'];");
 if(p.includes('voorspel_competitie'))s=s.replace(".where('competitie', isEqualTo: comp)",".where('division', isEqualTo: comp.endsWith('B') ? 'B' : 'A')");
 if(p.includes('poule_voorspellingen'))s=s.replace('if (!shareSnap.hasData)',"if (shareSnap.hasError) { return const Center(child: Text('Poule kon niet worden geladen.')); }\n          if (!shareSnap.hasData)").replace('if (!predSnap.hasData)',"if (predSnap.hasError) { return const Center(child: Text('Voorspellingen konden niet worden geladen.')); }\n              if (!predSnap.hasData)").replace('if (!matchSnap.hasData)',"if (matchSnap.hasError) { return const Center(child: Text('Wedstrijden konden niet worden geladen.')); }\n                  if (!matchSnap.hasData)");
 return s;
});
