const fs=require('fs');let s=fs.readFileSync('tools/audit_result_processing.cjs','utf8');
s=s.replace('let locked=false;','let locked=false,writesStarted=false,completed=false;');
s=s.replace("if(state.data()?.enabled)throw Error('Another repair already holds the maintenance lock');","if(state.data()?.enabled && !args.includes('--resume-maintenance'))throw Error('Maintenance active. Inspect the previous backup/report before --resume-maintenance');");
s=s.replace('const changes=[],issues=[],expectedTotals=new Map(),pouleTotals=new Map(),backup=[];','const changes=[],issues=[],expectedTotals=new Map(),pouleTotals=new Map(),backup=[],expectedLedgers=new Set(),bonusOwners=new Set();');
s=s.replace('const byDivision={A:{},B:{}};',`const knownPoules=new Set();
  for(const c of ['predictionContributions','pouleContributions'])for(const doc of await all(base+'/'+c))if(doc.data().pouleId)knownPoules.add(doc.data().pouleId);
  for(const doc of await all('poules'))if(doc.data().seasonId===ACTIVE_SEASON)knownPoules.add(doc.id);
  for(const id of knownPoules)for(const doc of await all('poules/'+id+'/deelnemers'))pouleTotals.set(doc.ref.path,0);
  const byDivision={A:{},B:{}};`);
s=s.replace('plan(ledger,ledgerData,','expectedLedgers.add(ledger);\n     plan(ledger,ledgerData,');
s=s.replace('plan(ledger,{userId:user,pouleId:poule,','expectedLedgers.add(ledger);\n     plan(ledger,{userId:user,pouleId:poule,');
s=s.replace("if(['A','B'].includes(div)){expected(user)","if(['A','B'].includes(div)){const key=div+'__'+user;if(bonusOwners.has(key)){issues.push({path:doc.ref.path,error:'Duplicate bonus ownership; verify manually'});continue;}bonusOwners.add(key);expected(user)");
s=s.replace("const data=user.data(),totals=expectedTotals.get(user.id)??{punten_A:0,punten_B:0};","const data=user.data(),totals=expectedTotals.get(user.id)??{punten_A:0,punten_B:0};\n   for(const div of ['A','B'])if(data[div==='A'?'eindstandA_awarded':'eindstandB_awarded'] && !bonusOwners.has(div+'__'+user.id))issues.push({path:user.ref.path,error:'Awarded bonus has no current-season marker'});");
s=s.replace("const selectedPath=d.predictionPath;\r\n   if(selectedPath && (await db.doc(selectedPath).get()).exists)continue;","if(expectedLedgers.has(doc.ref.path))continue;").replace("const selectedPath=d.predictionPath;\n   if(selectedPath && (await db.doc(selectedPath).get()).exists)continue;","if(expectedLedgers.has(doc.ref.path))continue;");
s=s.replace('const out=value(',"for(const id of expectedTotals.keys())if(!userById.has(id))issues.push({path:'users/'+id,error:'Missing prediction owner'});\n  const out=value(");
s=s.replace('for(let i=0;i<changes.length;i+=400){','for(let i=0;i<changes.length;i+=400){writesStarted=true;');
s=s.replace("console.log('Corrections completed.","completed=true;\n  console.log('Corrections completed.");
s=s.replace('if(locked)await lock.set','if(locked && (completed || !writesStarted))await lock.set');
fs.writeFileSync('tools/audit_result_processing.cjs',s);
